My Application: Outfit Class Reference
Outfit Class Reference
Class to define the class for Outfit.
#include <Outfit.h>
Public Member Functions
virtual ~Outfit ()
[DESTRUCTOR] Delete instance of Outfit class
Outfit (const string &outfitName="", const int &initialDurability_=0, const int &outfitSPECIALValue=0)
[CONSTRUCTOR] Intialize instance of Outfit class and instantiate member variables and takes in the name of outfit, initial durability and outfit SPECIAL value
const int getSPECIAL ()
[GETTER] Gets special value
void receiveDamage (const int &damageToItemDurability)
Apply damage to outfit's durability.
Public Member Functions inherited from Item
virtual ~Item ()
[DESTRUCTOR] Delete instance of Item class
Item (const string &kName="", const int &durability_=0)
[CONSTRUCTOR] Intialize instance of Item class and instantiate member variables and takes in name of object and initial durability value
const int getDurability ()
[GETTER] Gets durability value of item
Public Member Functions inherited from GameObject
virtual ~GameObject ()
[DESTRUCTOR] Delete instance of GameObject class
virtual string getName (void)
[GETTER] Get name of object
Private Attributes
const int kSPECIAL
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
[GETTER] Get number of of object of this type instantiated
Protected Member Functions inherited from GameObject
GameObject (const string &objectName="")
[CONSTRUCTOR](Override) Intialize instance of GameObject class and instantiate member variables and takes in the name of the object
Protected Attributes inherited from Item
int durability_
Detailed Description
Class to define the class for Outfit.
Class Outfit:
Definition at line 20 of file Outfit.h.
Constructor & Destructor Documentation
Outfit::~Outfit () virtual
[DESTRUCTOR] Delete instance of Outfit class
Definition at line 14 of file Outfit.cpp.
Outfit::Outfit (const string & outfitName = "", const int & initialDurability_ = 0, const int & outfitSPECIALValue = 0)
[CONSTRUCTOR] Intialize instance of Outfit class and instantiate member variables and takes in the name of outfit, initial durability and outfit SPECIAL value
Parameters
outfitName Name of outfit
initialDurability_ initial durability
outfitSPECIALValue Outfit's SPECIAL value
Definition at line 18 of file Outfit.cpp.
Member Function Documentation
const int Outfit::getSPECIAL ()
[GETTER] Gets special value
Definition at line 24 of file Outfit.cpp.
References kSPECIAL.
Referenced by testNames().
void Outfit::receiveDamage (const int & damageToItemDurability) virtual
Apply damage to outfit's durability.
Implements Item.
Definition at line 29 of file Outfit.cpp.
References Item::durability_.
Referenced by Dweller::receiveEquipmentDamage(), and testNames().
Field Documentation
const int Outfit::kSPECIAL private
Definition at line 66 of file Outfit.h.
Referenced by getSPECIAL().
The documentation for this class was generated from the following files:
Assignment1/Outfit.h
Assignment1/Outfit.cpp