My Application: Weapon Class Reference
Weapon Class Reference
Class to define the class for Weapon.
#include <Weapon.h>
Public Member Functions
Weapon (const string &weaponName="", const int &initialDurability_=0, const int &weaponDmg=0)
[CONSTRUCTOR](Override) Intialize instance of Weapon class and instantiate member and take in name of weapon, initial Durability and weapon damage
virtual ~Weapon ()
[DESTRUCTOR] Delete instance of Weapon
const int getAttackDmg ()
[GETTER] Get attack power/ damage value
void receiveDamage (const int &damageToItemDurability)
Apply Damage to weapon's durability.
Public Member Functions inherited from Item
virtual ~Item ()
[DESTRUCTOR] Delete instance of Item class
Item (const string &kName="", const int &durability_=0)
[CONSTRUCTOR] Intialize instance of Item class and instantiate member variables and takes in name of object and initial durability value
const int getDurability ()
[GETTER] Gets durability value of item
Public Member Functions inherited from GameObject
virtual ~GameObject ()
[DESTRUCTOR] Delete instance of GameObject class
virtual string getName (void)
[GETTER] Get name of object
Private Attributes
const int kAttackDmg
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
[GETTER] Get number of of object of this type instantiated
Protected Member Functions inherited from GameObject
GameObject (const string &objectName="")
[CONSTRUCTOR](Override) Intialize instance of GameObject class and instantiate member variables and takes in the name of the object
Protected Attributes inherited from Item
int durability_
Detailed Description
Class to define the class for Weapon.
Class Weapon:
Definition at line 21 of file Weapon.h.
Constructor & Destructor Documentation
Weapon::Weapon (const string & weaponName = "", const int & initialDurability_ = 0, const int & weaponDmg = 0)
[CONSTRUCTOR](Override) Intialize instance of Weapon class and instantiate member and take in name of weapon, initial Durability and weapon damage
Parameters
weaponName Name of Weapon
initialDurability intial durability of weapon
weaponDmg Damage dealt by weapon
Definition at line 17 of file Weapon.cpp.
Weapon::~Weapon () virtual
[DESTRUCTOR] Delete instance of Weapon
Definition at line 13 of file Weapon.cpp.
Member Function Documentation
const int Weapon::getAttackDmg ()
[GETTER] Get attack power/ damage value
Definition at line 22 of file Weapon.cpp.
References kAttackDmg.
Referenced by Dweller::getAttackDmg(), and testNames().
void Weapon::receiveDamage (const int & damageToItemDurability) virtual
Apply Damage to weapon's durability.
Parameters
damageToItemDurability Damage to be dealt to durability
Implements Item.
Definition at line 28 of file Weapon.cpp.
References Item::durability_.
Referenced by testNames().
Field Documentation
const int Weapon::kAttackDmg private
Definition at line 70 of file Weapon.h.
Referenced by getAttackDmg().
The documentation for this class was generated from the following files:
Assignment1/Weapon.h
Assignment1/Weapon.cpp